# Generated by Django 2.2.16 on 2022-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0002_auto_20221110_0612")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/", verbose_name="Картинка"
            ),
        )
    ]
